version: 2
updates:
  # TypeScript dependencies managed by npm
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    reviewers:
      - "issacli-0821"
      - "G-Marin"
      - "windsornguyen"
      - "ggchiriac"
    open-pull-requests-limit: 5

  # Python dependencies managed by pip
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    reviewers:
      - "issacli-0821"
      - "G-Marin"
      - "windsornguyen"
      - "ggchiriac"
    open-pull-requests-limit: 5
