version: 2
updates:

  # TypeScript dependencies managed by npm
  - package-ecosystem: "npm"
    directory: "frontend/"
    target-branch: "preview"
    schedule:
      interval: "monthly"
      day: "tuesday"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    reviewers:
      - "issacli-0821"
      - "Spencer04Hire"
      - "hannahchoi05"
      - "emiilyyou"
    open-pull-requests-limit: 0

  # Python dependencies managed by pip
  - package-ecosystem: "pip"
    directory: "backend/"
    target-branch: "preview"
    schedule:
      interval: "monthly"
      day: "thursday"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    reviewers:
      - "issacli-0821"
      - "Spencer04Hire"
      - "hannahchoi05"
      - "emiilyyou"
    open-pull-requests-limit: 0
