# Runtime configurations

# Scripts to run before `bun run`-ing a file or script
# register plugins by adding them to this list
preload = [""]

# Configure how Bun handles JSX
jsx = "react"
jsxFactory = "h"
jsxFragment = "Fragment"
jsxImportSource = "react"

# Reduce memory usage at the cost of performance
smol = false

# Set the log level
logLevel = "debug" # "debug" | "warn" | "error"

[define]
# Replace any usage of "process.env.bagel" with the string `lox`.
# The values are parsed as JSON, except single-quoted strings are supported and `'undefined'` becomes `undefined` in JS.
# This will probably change in a future release to be just regular TOML instead. It is a holdover from the CLI argument parsing.
"process.env.bagel" = "'lox'"

[loader]
# when a .bagel file is imported, treat it like a tsx file
".bagel" = "tsx"

# Test configurations
[test]
root = "./__tests__"
preload = ["./setup.ts"]
smol = true
coverage = true
coverageThreshold = {line = 0.7, function = 0.8, statement = 0.9}
coverageSkipTestFiles = false

# Package manager configurations
[install]
optional = true
dev = true
peer = true
production = false
exact = false
auto = "auto"
frozenLockfile = false
dryRun = false
globalDir = "~/.bun/install/global"
globalBinDir = "~/.bun/bin"
registry = "https://registry.npmjs.org"

[install.scopes]
"@myorg" = "$MYORG_REGISTRY"

[install.cache]
dir = "~/.bun/install/cache"

[install.lockfile]
save = true
print = "yarn"
