// TODO: Should probably id these corresponding to the ids in the database, may be used in other files
export const MAJOR_OPTIONS = [
	{ code: 'AAS', name: 'African American Studies' },
	{ code: 'ANT', name: 'Anthropology' },
	{ code: 'ARC', name: 'Architecture' },
	{ code: 'ART', name: 'Art and Archaeology' },
	{ code: 'AST', name: 'Astrophysical Sciences' },
	{ code: 'CBE', name: 'Chemical and Biological Engineering' },
	{ code: 'CEE', name: 'Civil and Environmental Engineering' },
	{ code: 'CHM', name: 'Chemistry' },
	{ code: 'CLA', name: 'Classics' },
	{ code: 'COM', name: 'Comparative Literature' },
	{ code: 'COS-AB', name: 'Computer Science - A.B.' },
	{ code: 'COS-BSE', name: 'Computer Science - B.S.E.' },
	{ code: 'EAS', name: 'East Asian Studies' },
	{ code: 'ECE', name: 'Electrical and Computer Engineering' },
	{ code: 'ECO', name: 'Economics' },
	{ code: 'EEB', name: 'Ecology and Evolutionary Biology' },
	{ code: 'ENG', name: 'English' },
	{ code: 'FIT', name: 'French and Italian' },
	{ code: 'GEO', name: 'Geosciences' },
	{ code: 'GER', name: 'German' },
	{ code: 'HIS', name: 'History' },
	{ code: 'LIN', name: 'Linguistics' },
	{ code: 'MAE', name: 'Mechanical and Aerospace Engineering' },
	{ code: 'MAT', name: 'Mathematics' },
	{ code: 'MOL', name: 'Molecular Biology' },
	{ code: 'MUS', name: 'Music' },
	{ code: 'NES', name: 'Near Eastern Studies' },
	{ code: 'NEU', name: 'Neuroscience' },
	{ code: 'ORF', name: 'Operations Research and Financial Engineering' },
	{ code: 'PHI', name: 'Philosophy' },
	{ code: 'PHY', name: 'Physics' },
	{ code: 'POL', name: 'Politics' },
	{ code: 'POR', name: 'Portuguese' },
	{ code: 'PSY', name: 'Psychology' },
	{ code: 'REL', name: 'Religion' },
	{ code: 'SLA', name: 'Slavic Languages and Literatures' },
	{ code: 'SOC', name: 'Sociology' },
	{ code: 'SPA', name: 'Spanish' },
	{ code: 'SPI', name: 'School of Public and International Affairs' },
	// { code: 'Independent', name: 'Independent' }, TODO: This is an actual major here and should be added.
	{ code: 'Undeclared', name: 'Undeclared' },
];

export const MINOR_OPTIONS = [
	{ code: 'AAS', name: 'African American Studies' },
	{ code: 'AFS', name: 'African Studies' },
	{ code: 'APC', name: 'Applied and Computational Mathematics' },
	{ code: 'ARA', name: 'Arabic Language' },
	{ code: 'ASA', name: 'Asian American Studies' },
	{ code: 'ART', name: 'Archaeology' },
	{ code: 'BNG', name: 'Bioengineering' },
	{ code: 'CGS', name: 'Cognitive Science' },
	{ code: 'CHI', name: 'Chinese Language' },
	{ code: 'CLA', name: 'Classics' },
	{ code: 'COS', name: 'Computer Science' },
	{ code: 'CS', name: 'Climate Science' },
	{ code: 'CWR', name: 'Creative Writing' },
	{ code: 'DAN', name: 'Dance' },
	{ code: 'EAS', name: 'East Asian Studies' },
	{ code: 'ENE', name: 'Sustainable Energy' },
	{ code: 'ENG', name: 'English' },
	{ code: 'ENV', name: 'Environmental Studies' },
	{ code: 'EUS', name: 'European Studies' },
	{ code: 'FIN', name: 'Finance' },
	{ code: 'FRE', name: 'French Language and Culture' },
	{ code: 'GHP', name: 'Global Health & Health Policy' },
	{ code: 'GSS', name: 'Gender and Sexuality Studies' },
	{ code: 'HOA', name: 'History of Art' },
	{ code: 'HEB', name: 'Hebrew Language and Culture' },
	{ code: 'HIS', name: 'History' },
	{ code: 'HLS', name: 'Hellenic Studies' },
	{ code: 'HSTM', name: 'History of Science, Technology, and Medicine' },
	{ code: 'HUM', name: 'Humanistic Studies' },
	{ code: 'ITA', name: 'Italian Language and Culture' },
	{ code: 'JDS', name: 'Judaic Studies' },
	{ code: 'JPN', name: 'Japanese Language' },
	{ code: 'JRN', name: 'Journalism' },
	{ code: 'KOR', name: 'Korean Language' },
	{ code: 'LAO', name: 'Latino Studies' },
	{ code: 'LAS', name: 'Latin American Studies' },
	{ code: 'LIN', name: 'Linguistics' },
	{ code: 'MAT', name: 'Mathematics' },
	{ code: 'MED', name: 'Medieval Studies' },
	{ code: 'MPP', name: 'Music Performance' },
	{ code: 'MQE', name: 'Quantitative Economics' },
	{ code: 'MSE', name: 'Materials Science and Engineering' },
	{ code: 'MUS', name: 'Music' },
	{ code: 'NES', name: 'Near Eastern Studies' },
	{ code: 'NEU', name: 'Neuroscience' },
	{ code: 'PER', name: 'Persian Language' },
	{ code: 'PHI', name: 'Philosophy' },
	{ code: 'PHY', name: 'Engineering Physics' },
	{ code: 'POR', name: 'Portuguese Language and Culture' },
	{ code: 'REL', name: 'Religion' },
	{ code: 'RES', name: 'Russian, East European and Eurasian Studies' },
	{ code: 'ROB', name: 'Robotics' },
	{ code: 'SAS', name: 'South Asian Studies' },
	{ code: 'SLA', name: 'Slavic Languages and Literatures' },
	{ code: 'SML', name: 'Statistics and Machine Learning' },
	{ code: 'SPA', name: 'Spanish Language and Culture' },
	{ code: 'TMT', name: 'Theater and Music Theater' },
	{ code: 'TRA', name: 'Translation and Intercultural Communication' },
	{ code: 'TUR', name: 'Turkish Language' },
	{ code: 'VIS', name: 'Visual Arts' },
	{ code: 'VPL', name: 'Values and Public Life' },
];

export const CERTIFICATE_OPTIONS = [
	{
		code: 'ACE',
		name: 'Architecture and Engineering - Open to all class years',
	},
	{ code: 'AMS', name: 'American Studies - Open to all class years' },
	{ code: 'AST', name: 'Planets and Life - Open to Class of 26, 27, 28 only' },
	{ code: 'ENT', name: 'Entrepreneurship - Open to all class years' },
	{ code: 'GEO', name: 'Geological Engineering - Open to all class years' },
	{ code: 'GER', name: 'German - Open to all class years' },
	{
		code: 'HPD',
		name: 'History and the Practice of Diplomacy - Open to all class years',
	},
	{
		code: 'OQDS',
		name: 'Optimization and Quantitative Decision Science - Open to all class years',
	},
	{
		code: 'QCB',
		name: 'Quantitative and Computational Biology - Open to all class years',
	},
	{
		code: 'TAS-E',
		name: 'Technology and Society - Energy Track - Open to all class years',
	},
	{
		code: 'TAS-IT',
		name: 'Technology and Society - IT Track - Open to all class years',
	},
	{ code: 'TPP', name: 'Teacher Preparation - Open to all class years' },
	{ code: 'URB', name: 'Urban Studies - Open to all class years' },
];
