# Generated by Django 5.1.1 on 2025-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0011_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='requirement',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='hoagieplan.requirement'),
        ),
    ]
