# Generated by Django 5.1.1 on 2025-08-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0012_remove_usercourses_requirement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semesterconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='semesterconfiguration',
            name='calendar_configuration',
        ),
        migrations.RemoveField(
            model_name='semesterconfiguration',
            name='term',
        ),
        migrations.AlterUniqueTogether(
            name='calendarconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calendarconfiguration',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoagieplan.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarconfiguration',
            unique_together={('user', 'name', 'term')},
        ),
        migrations.CreateModel(
            name='UserCalendarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_calendar_section', to='hoagieplan.calendarconfiguration')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoagieplan.section')),
            ],
            options={
                'db_table': 'UserCalendarSection',
                'unique_together': {('calendar_configuration', 'section')},
            },
        ),
        migrations.DeleteModel(
            name='ScheduleSelection',
        ),
        migrations.DeleteModel(
            name='SemesterConfiguration',
        ),
    ]
