# Generated by Django 5.1.1 on 2025-09-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0013_alter_semesterconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True, null=True)),
                ('end_time', models.TimeField(db_index=True, null=True)),
                ('start_column_index', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('needs_choice', models.BooleanField(default=False)),
                ('is_chosen', models.BooleanField(default=False)),
                ('calendar_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='hoagieplan.calendarconfiguration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoagieplan.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoagieplan.section')),
            ],
            options={
                'db_table': 'calendar_event',
                'unique_together': {('calendar_configuration', 'course', 'section')},
            },
        ),
        migrations.DeleteModel(
            name='UserCalendarSection',
        ),
    ]
