# Generated by Django 5.1.1 on 2025-11-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0014_calendarevent_delete_usercalendarsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('calendar_configuration', 'course', 'section', 'start_column_index')},
        ),
    ]
