# Generated by Django 5.1.1 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0016_delete_courseevaluations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='contacts',
            field=models.JSONField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='contacts',
            field=models.JSONField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='minor',
            name='contacts',
            field=models.JSONField(db_index=True, null=True),
        ),
    ]
