# Generated by Django 5.1.1 on 2026-03-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0017_certificate_contacts_major_contacts_minor_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="hoagieplan.course",
                    ),
                ),
            ],
            options={
                "db_table": "CourseComment",
            },
        ),
        migrations.CreateModel(
            name="CourseEvalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eval_summary",
                        to="hoagieplan.course",
                    ),
                ),
            ],
            options={
                "db_table": "CourseEvalSummary",
            },
        ),
        migrations.DeleteModel(
            name="CourseComments",
        ),
    ]
