# Generated by Django 5.1.1 on 2026-02-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0017_certificate_contacts_major_contacts_minor_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="hoagieplan.instructor"
            ),
        ),
    ]
