# Generated by Django 5.1.1 on 2026-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagieplan', '0018_coursecomment_courseevalsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
