# Generated by Django 5.1.1 on 2026-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0019_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="hoagieplan.instructor"
            ),
        ),
    ]
