# Generated by Django 5.1.1 on 2026-03-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0020_course_instructors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="instructor",
        ),
    ]
