# Generated by Django 6.0.3 on 2026-03-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0021_remove_section_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
