# Generated by Django 6.0.3 on 2026-04-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0022_alter_requirement_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grading_final_exam", models.IntegerField(default=0)),
                ("grading_mid_exam", models.IntegerField(default=0)),
                ("grading_home_final_exam", models.IntegerField(default=0)),
                ("grading_home_mid_exam", models.IntegerField(default=0)),
                ("grading_other_exam", models.IntegerField(default=0)),
                ("grading_paper_final_exam", models.IntegerField(default=0)),
                ("grading_paper_mid_exam", models.IntegerField(default=0)),
                ("grading_oral_pres", models.IntegerField(default=0)),
                ("grading_quizzes", models.IntegerField(default=0)),
                ("grading_lab_reports", models.IntegerField(default=0)),
                ("grading_papers", models.IntegerField(default=0)),
                ("grading_prob_sets", models.IntegerField(default=0)),
                ("grading_prog_assign", models.IntegerField(default=0)),
                ("grading_precept_part", models.IntegerField(default=0)),
                ("grading_term_papers", models.IntegerField(default=0)),
                ("grading_design_projects", models.IntegerField(default=0)),
                ("grading_other", models.IntegerField(default=0)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_info",
                        to="hoagieplan.course",
                    ),
                ),
            ],
            options={
                "db_table": "GradingInfo",
            },
        ),
    ]
