# Generated by Django 6.0.3 on 2026-04-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoagieplan", "0023_gradinginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="iw_required",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="minor",
            name="iw_required",
            field=models.BooleanField(null=True),
        ),
    ]
